### ISSUE TITLE
Terminal/README.md instructions

### ISSUE THREAD

**Issue by ixp-nl** [leofeyer/darcula-ftw#2]
The instruction to double click the .terminal file in Terminal/README.md doesn't work (anymore).
Instead you need to import it, because it's from unidentified developer.
```“Darcula.terminal” cannot be opened because it is from an unidentified developer.```
Thanks for making this theme public 🥰

**Comment by leofeyer** [comment]
Fixed in eaa4861a070f3edae73cc0f201dfb1ce67dbd92c. Thank you @ixp-nl.
